### ISSUE TITLE
Error al fimar

### ISSUE THREAD

**Issue by ramal04** [ctt-gob-es/portafirmas-ios#45]
En la version 1.5.2, en iOS, al firmar aparece el mensaje : "Se ha producido un error en el servidor: Se ha recibido un certificado corrupto (ERR-04)". Las trazas en el servidor son las siguientes: 
GRAVE: <err cd="ERR-04">Se ha recibido un certificado corrupto</err>: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Incomplete BER/DER data
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Incomplete BER/DER data

**Comment by Gamuci** [comment]
El error se debe a un cambio en la codificación se los base 64 que se hace en iOS 13.3 y superiores. Se hace de tal forma que algunas versiones antiguas de los servicios proxy no lo soportan.

Se ha publicado una versión 1.5.3 del Portafirmas iOS en el que ya no se produce el error.

**Comment by ramal04** [comment]
Donde están las versiones más recientes del proxy?
